<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZFB2'); ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/bower_components/bootstrap/dist/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>

        <?php echo $this->headScript()->prependFile($this->basePath() . '/bower_components/bootstrap/dist/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/bower_components/jquery/dist/jquery.min.js') ?>

    </head>
    <body>

        <?php echo $this->content; ?>
        <?php echo $this->inlineScript(); ?>
    </body>
</html>
